name: CleanBuild
run-name: CleanBuild
on: 
  push:
    branches: 
      - main
jobs:
  GenerateRelease:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "PWD is [ ${{ github.workspace }} ]"
          ls -al .

      ### Create Build Files
      - name: Zip CleanBuild 
        uses: montudor/action-zip@v1
        with: 
          args: zip -qq -r cleanbuild.zip CleanBuild/CleanBuild.ps1 CleanBuild/icon.ico    

      ### Create Tag and Release 
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          WITH_V: true
          PRERELEASE: false      
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: | 
            cleanbuild.zip
